services:
  database:
    image: postgres:17.9-alpine3.23
    container_name: container_condominium

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: condominium
      POSTGRES_PASSWORD: local

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: condominium_postgres_data
